// Astra seed registry: agents, skills, phone permissions.
// Built-in skills with an `exec` id have real executors in generate.ts.

export const PERMS: any[] = [
  { key: 'contacts', name: 'Contacts', icon: 'users', web: false, desc: 'Look up, add and manage your contacts.' },
  { key: 'files', name: 'Files & Storage', icon: 'folder', web: true, desc: 'Read and manage files you attach or create with Astra.' },
  { key: 'notifications', name: 'Notifications', icon: 'bell', web: true, desc: 'Send you push notifications when tasks complete or need approval.' },
  { key: 'calls', name: 'Calls', icon: 'phone', web: false, desc: 'Make and receive calls on your behalf (mobile companion only).' },
  { key: 'messages', name: 'Messages', icon: 'message', web: false, desc: 'Send and read messages (mobile companion only).' },
  { key: 'camera', name: 'Camera', icon: 'camera', web: true, desc: 'Take photos and videos when you ask.' },
  { key: 'location', name: 'Location', icon: 'pin', web: true, desc: 'Access location for local research and reminders.' },
  { key: 'screen', name: 'Screen Access', icon: 'eye', web: false, desc: 'Read screen content to help with on-screen tasks (mobile companion only).' },
];

export const SKILLS: any[] = [
  {
    id: 'web-research', name: 'Web & Research', icon: 'search', version: '2.1.0', exec: 'research',
    desc: 'Real-time web research compiled into sourced reports.',
    instructions: 'Identify the subject, fetch authoritative sources, extract key facts, structure an overview, analysis and sources section. Cite every fact.',
    tools: ['web.fetch', 'knowledge.compile', 'report.write'], permissions: [],
    examples: ['Research the top trading platforms in Ghana', 'Summarize the EV market in 2026'],
    quality: ['Every claim cites a source', 'Overview + analysis + sources structure', 'No fabricated citations'],
    output: 'Markdown research report (.md) with sources',
  },
  {
    id: 'coding', name: 'Coding & Development', icon: 'code', version: '3.0.2', exec: 'website',
    desc: 'Write, test and fix production code (HTML/CSS/JS, APIs).',
    instructions: 'Generate clean semantic code, run the static test suite, fix every critical finding before delivery.',
    tools: ['code.write', 'code.test', 'console.read'], permissions: ['files'],
    examples: ['Add a pricing calculator to my site', 'Fix the mobile menu bug'],
    quality: ['No console errors', 'Valid markup', 'Accessible semantics'],
    output: 'Source files + test report',
  },
  {
    id: 'web-development', name: 'Web Development', icon: 'globe', version: '3.4.1', exec: 'website',
    desc: 'Build complete responsive websites and web apps: HTML/CSS/JS, React-style components, APIs, testing, deployment.',
    instructions: 'Understand requirements, research the business, design tokens, generate responsive semantic code, test (validator + console), review, fix, preview, deploy on request.',
    tools: ['code.write', 'code.test', 'preview.serve', 'deploy.publish'], permissions: ['files'],
    examples: ['Build a website for my printing business', 'Build a booking web app'],
    quality: ['Responsive', 'No broken links', 'No console errors', 'Good UX', 'Accessible', 'Fast', 'Secure (no untrusted external scripts)'],
    output: 'Deployable site (index.html, styles.css, app.js)',
  },
  {
    id: 'uiux-design', name: 'UI/UX Design', icon: 'pen', version: '1.8.0', exec: 'design',
    desc: 'Create UI kits, design tokens and interface mockups.',
    instructions: 'Derive palette and typography from the brief, produce a visual design kit artifact.',
    tools: ['design.tokens', 'design.render'], permissions: [],
    examples: ['Design a dark fintech UI kit', 'Logo for a coffee brand'],
    quality: ['Consistent spacing scale', 'Contrast-safe palette', 'Coherent typography'],
    output: 'Design kit (SVG) + tokens',
  },
  {
    id: 'image-generation', name: 'Image Generation', icon: 'image', version: '2.6.0', exec: 'image',
    desc: 'Generate images and logos as real vector artifacts.',
    instructions: 'Seed a deterministic composition from the prompt, honor style + aspect ratio, embed a title for accessibility.',
    tools: ['image.render', 'file.write'], permissions: ['files'],
    examples: ['Modern logo for a trading app', 'Futuristic city poster 16:9'],
    quality: ['Valid SVG', 'Matches aspect ratio', 'Includes accessible title'],
    output: 'Image file (.svg)',
  },
  {
    id: 'video', name: 'Video & Motion', icon: 'video', version: '0.9.4', exec: 'motion',
    desc: 'Produce animated motion previews (honest label: full video render requires the GPU service).',
    instructions: 'Compose an animated storyboard as an SVG motion preview; state clearly that it is a motion preview, not a rendered video.',
    tools: ['motion.render'], permissions: ['files'],
    examples: ['10s animated intro for my channel'],
    quality: ['Animates smoothly', 'Honest format labeling'],
    output: 'Animated motion preview (.svg)',
  },
  {
    id: 'documents', name: 'Documents', icon: 'file', version: '2.2.3', exec: 'document',
    desc: 'Create real PDF, Word (.docx), Excel (.xlsx) and presentation files.',
    instructions: 'Structure title + sections, export every requested format with real file writers.',
    tools: ['doc.pdf', 'doc.docx', 'doc.xlsx', 'doc.slides'], permissions: ['files'],
    examples: ['Write a project proposal PDF', 'Quarterly budget spreadsheet'],
    quality: ['Complete sections', 'No placeholder text', 'Valid file formats'],
    output: '.pdf / .docx / .xlsx / slides.html',
  },
  {
    id: 'data-analysis', name: 'Data Analysis', icon: 'chart', version: '1.5.1', exec: 'data',
    desc: 'Compute real statistics over provided data and render charts.',
    instructions: 'Parse numbers/CSV, compute count/sum/mean/min/max/stddev, render a chart artifact.',
    tools: ['stats.compute', 'chart.render'], permissions: ['files'],
    examples: ['Analyze these sales figures: 12, 19, 3, 5, 2, 3'],
    quality: ['Correct math', 'Chart matches data'],
    output: 'Stats summary + chart (.svg)',
  },
  {
    id: 'automation', name: 'Automation', icon: 'zap', version: '2.0.0', exec: 'automation',
    desc: 'Schedule recurring work: triggers, conditions, actions, notifications.',
    instructions: 'Parse schedule from natural language, register the automation with the scheduler, confirm next run time.',
    tools: ['scheduler.register', 'notify.send'], permissions: ['notifications'],
    examples: ['Every morning at 8 AM research the markets and send me a report'],
    quality: ['Next run time stated', 'Respects notification permission'],
    output: 'Live automation entry',
  },
  {
    id: 'browser-control', name: 'Browser Control', icon: 'compass', version: '0.7.0', exec: null,
    desc: 'Operate a browser to complete web tasks (requires the browser runtime service).',
    instructions: 'Not connected in this environment; the agent must state the missing runtime instead of pretending.',
    tools: ['browser.navigate', 'browser.click'], permissions: ['screen'],
    examples: ['Fill the form on my bank site'],
    quality: ['Honest capability reporting'],
    output: '—',
  },
  {
    id: 'security-audit', name: 'Security Audit', icon: 'shield', version: '1.2.0', exec: 'security',
    desc: 'Audit generated code and your Astra configuration for security issues.',
    instructions: 'Scan artifacts for external scripts, inline secrets, unsafe patterns; report findings.',
    tools: ['code.scan', 'audit.read'], permissions: [],
    examples: ['Audit my website build'],
    quality: ['Actionable findings', 'Severity levels'],
    output: 'Audit report',
  },
  {
    id: 'review-qa', name: 'Review & QA', icon: 'checkshield', version: '2.9.0', exec: 'review',
    desc: 'Independent quality gate. Inspects every result before delivery; failed work is sent back for fixes.',
    instructions: 'Run the checklist for the artifact type. Critical finding => block delivery and send back to the producing agent. Re-review after fixes.',
    tools: ['artifact.inspect', 'checklist.run'], permissions: [],
    examples: ['Review the website build'],
    quality: ['Never approve broken work', 'Explain every finding'],
    output: 'Review verdict + findings',
  },
];

// ---------- Open-source adapted skills (researched, license-checked) ----------
// Each entry records its source repository and license. Instructions were
// rewritten for Astra's own executor pipeline (xKiro backend) — no Claude
// dependency. See /docs/THIRD_PARTY_SKILLS.md for the full audit.
export const OPEN_SOURCE_SKILLS: any[] = [
  {
    id: 'frontend-craft', name: 'Frontend Craft', icon: 'spark', version: '1.0.0', exec: 'design', market: true,
    provenance: { repo: 'anthropics/skills (frontend-design, Apache-2.0) + ConardLi/garden-skills (web-design-engineer, MIT)', license: 'Apache-2.0 / MIT', adapted: true },
    desc: 'Production-grade visual/UX standards for every interface Astra designs.',
    instructions: 'Design with a defined type scale, consistent spacing rhythm and accessible contrast. Avoid generic layouts: pick one strong visual idea, apply it consistently, and keep interactions responsive with visible feedback.',
    tools: ['design.render'], permissions: [],
    examples: ['Redesign my landing hero', 'Design a premium dashboard theme'],
    quality: ['Clear visual hierarchy', 'Consistent spacing and type scale', 'WCAG AA contrast', 'No placeholder-gray filler'],
    output: 'Design direction + rendered artifact',
  },
  {
    id: 'webapp-testing', name: 'Web App Testing', icon: 'check', version: '1.0.0', exec: 'review', market: true,
    provenance: { repo: 'anthropics/skills (webapp-testing, Apache-2.0)', license: 'Apache-2.0', adapted: true },
    desc: 'Systematic functional testing of generated web apps before delivery.',
    instructions: 'Enumerate user flows, exercise each control and form, capture console errors and broken links, verify responsive breakpoints, and report pass/fail per flow with reproduction steps. Fail the review if any critical flow breaks.',
    tools: ['artifact.inspect', 'checklist.run', 'code.test'], permissions: [],
    examples: ['Test the signup flow of my build', 'Audit my deployed site'],
    quality: ['Every primary flow tested', 'Console errors reported verbatim', 'Mobile + desktop checked'],
    output: 'Test report with pass/fail per flow',
  },
  {
    id: 'api-design', name: 'API Design', icon: 'code', version: '1.0.0', exec: 'website', market: true,
    provenance: { repo: 'JayRHa/AgentSkills (api-designer, MIT)', license: 'MIT', adapted: true },
    desc: 'Clean, documented REST/JSON API contracts for generated backends.',
    instructions: 'Model resources as nouns, use correct HTTP verbs and status codes, version endpoints, keep payloads consistent, and document every route with example request/response pairs.',
    tools: ['code.write', 'code.test'], permissions: [],
    examples: ['Design an API for a booking app', 'Document my endpoints'],
    quality: ['Consistent resource naming', 'Correct status codes', 'Every route documented with examples'],
    output: 'OpenAPI-style contract + sample client',
  },
  {
    id: 'kb-retrieval', name: 'Knowledge Retrieval', icon: 'book', version: '1.0.0', exec: 'research', market: true,
    provenance: { repo: 'ConardLi/garden-skills (kb-retriever, MIT)', license: 'MIT', adapted: true },
    desc: 'Structured retrieval over Astra knowledge base and user documents.',
    instructions: 'Break the question into retrieval keys, query the knowledge base and uploaded files first, quote the exact passages found, and only fall back to web research when local sources are insufficient.',
    tools: ['web.fetch', 'knowledge.compile'], permissions: [],
    examples: ['What did we decide about pricing?', 'Summarize my uploaded brief'],
    quality: ['Local sources queried first', 'Quotes attributed to file', 'Gaps stated honestly'],
    output: 'Retrieval summary with citations',
  },
  {
    id: 'browser-router', name: 'Browser Automation Router', icon: 'compass', version: '1.0.0', exec: 'browser', market: true,
    provenance: { repo: 'browsing-skills/browsing-skills (MIT)', license: 'MIT', adapted: true },
    desc: 'Per-site playbooks for browser tasks, routed by domain.',
    instructions: 'Resolve the target domain, load its site-specific playbook (selectors, rate limits, login requirements), execute the smallest safe action sequence, and report exactly what was and was not done. If no browser runtime is connected, say so instead of pretending.',
    tools: ['browser.navigate'], permissions: ['browser'],
    examples: ['Open my LinkedIn notifications', 'Capture the trending page on X'],
    quality: ['Domain playbook used', 'Actions logged step by step', 'Honest capability reporting'],
    output: 'Action log + captured content',
  },
  {
    id: 'image-recipes', name: 'Image Composition Recipes', icon: 'image', version: '1.0.0', exec: 'image', market: true,
    provenance: { repo: 'anthropics/skills (canvas-design, algorithmic-art, Apache-2.0) + ConardLi/garden-skills (gpt-image-2, MIT)', license: 'Apache-2.0 / MIT', adapted: true },
    desc: 'Compositional and generative-imagery recipes for every rendered image.',
    instructions: 'Choose a composition strategy (rule of thirds, centered subject, layered depth), define palette and lighting before drawing, add subtle grain or gradient ambience, and keep text minimal and legible.',
    tools: ['image.render'], permissions: [],
    examples: ['Poster for a launch event', 'Abstract hero background'],
    quality: ['Intentional composition', 'Coherent palette', 'Legible minimal text'],
    output: 'Rendered image artifact',
  },
  {
    id: 'video-story', name: 'Video Storyboarding', icon: 'video', version: '1.0.0', exec: 'video', market: true,
    provenance: { repo: 'ConardLi/garden-skills (web-video-presentation, MIT)', license: 'MIT', adapted: true },
    desc: 'Storyboard-first motion production for explainer and promo pieces.',
    instructions: 'Write the narrative beat sheet first, storyboard each scene with framing notes, choose transitions that serve the story, and deliver a timed shot list before any rendering.',
    tools: ['motion.render'], permissions: [],
    examples: ['30s promo for my app', 'Explainer for onboarding'],
    quality: ['Beat sheet before frames', 'Timed shot list', 'Transitions motivated'],
    output: 'Storyboard + motion preview',
  },
  {
    id: 'beautiful-article', name: 'Beautiful Article', icon: 'file', version: '1.0.0', exec: 'document', market: true,
    provenance: { repo: 'ConardLi/garden-skills (beautiful-article, MIT)', license: 'MIT', adapted: true },
    desc: 'Editorial-quality long-form documents with real typography.',
    instructions: 'Structure with a strong lead, short sections and pull quotes; keep paragraphs under five lines; use headings that tell the story alone; format for both screen and print export.',
    tools: ['doc.docx', 'doc.pdf'], permissions: [],
    examples: ['Turn my notes into a feature article', 'Write a polished report'],
    quality: ['Lead paragraph hooks', 'Scannable headings', 'Consistent typography'],
    output: 'Formatted document (.docx/.pdf)',
  },
];
for (const s of OPEN_SOURCE_SKILLS) SKILLS.push(s);

export const AGENTS: any[] = [
  { id: 'research', name: 'Research Agent', icon: 'search', color: '#38bdf8', skills: ['web-research', 'data-analysis'], tools: ['web.fetch', 'report.write'], desc: 'Finds, verifies and compiles information into sourced reports.' },
  { id: 'coding', name: 'Coding Agent', icon: 'code', color: '#818cf8', skills: ['coding'], tools: ['code.write', 'code.test'], desc: 'Writes and fixes production-grade code.' },
  { id: 'design', name: 'Design Agent', icon: 'pen', color: '#f472b6', skills: ['uiux-design', 'image-generation'], tools: ['design.render', 'image.render'], desc: 'Creates interfaces, kits, logos and imagery.' },
  { id: 'web', name: 'Web Agent', icon: 'globe', color: '#34d399', skills: ['web-development'], tools: ['code.write', 'preview.serve', 'deploy.publish'], desc: 'Builds, tests and deploys websites and web apps.' },
  { id: 'video', name: 'Video Agent', icon: 'video', color: '#fb7185', skills: ['video'], tools: ['motion.render'], desc: 'Produces motion previews and storyboards.' },
  { id: 'document', name: 'Document Agent', icon: 'file', color: '#fbbf24', skills: ['documents'], tools: ['doc.pdf', 'doc.docx', 'doc.xlsx'], desc: 'Writes and exports real documents and spreadsheets.' },
  { id: 'data', name: 'Data Agent', icon: 'chart', color: '#22d3ee', skills: ['data-analysis'], tools: ['stats.compute', 'chart.render'], desc: 'Computes statistics and renders charts from your data.' },
  { id: 'automation', name: 'Automation Agent', icon: 'zap', color: '#a78bfa', skills: ['automation'], tools: ['scheduler.register', 'notify.send'], desc: 'Runs recurring work on schedules and triggers.' },
  { id: 'browser', name: 'Browser Agent', icon: 'compass', color: '#94a3b8', skills: ['browser-control'], tools: ['browser.navigate'], desc: 'Operates browsers (runtime not connected here — reports honestly).' },
  { id: 'security', name: 'Security Agent', icon: 'shield', color: '#4ade80', skills: ['security-audit'], tools: ['code.scan', 'audit.read'], desc: 'Audits code and configuration for risk.' },
  { id: 'review', name: 'Review Agent', icon: 'checkshield', color: '#e7c873', skills: ['review-qa'], tools: ['artifact.inspect', 'checklist.run'], desc: 'Independent quality gate before any delivery.' },
  { id: 'phone', name: 'Phone Control Agent', icon: 'phone', color: '#60a5fa', skills: [], tools: ['phone.contacts', 'phone.camera', 'phone.location'], desc: 'Bridges phone capabilities under your permission rules.' },
];

export const skillById = (id: string) => SKILLS.find((s) => s.id === id);
export const agentById = (id: string) => AGENTS.find((a) => a.id === id);
